### ISSUE TITLE
Assess the possibility of delivering small amounts of power over a wide area, with a laser, or microwave solar power satellite

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#2]
This issue documents a short peace of analysis to assess the possibility of beaming a small amount of power over a wide area using a single solar power satellite.

For the arbitrary power requirement of 10W, this issue aims to assess over what area a given laser, at a given distance can beam this amount of power to, for a transmitted power in the range of 10kW.

**Comment by darianvp** [comment]
Rover_Power: I look at the casting a Gaussian laser/microwave beam onto the surface of the moon for powering modular rovers via solar power satellite. The aim is to power 10 W lunar rovers across a ~km area. In analysis I first calculate the possible increase in beam radius when shining a 10 kW laser onto a larger spot which contains a flux of 10 W/m^2, using Gaussian beam divergence and conservation of flux. Then, I look at the altitude at which an SPS would have to fly in order for a mm/cm scale transmitter aperture to diverge into a beam on the order of km at the surface, for both laser (850 nm) and microwave (122 um) wavelengths. Then I determine the flux within the surface beam for a 10 MW transmitter power. 10 MW is chosen so that the resulting flux is compatible with the 10 W rover power metric from iSpace.

![relevanteqns](https://user-images.githubusercontent.com/38875772/39525525-79cdd05c-4e1c-11e8-8c5e-cdb3336417af.gif)

**Comment by darianvp** [comment]
Beam_Divergence_Brandhorst_Verification: In this script I try to verify the "Laser Beaming Results" from the Brandhorst paper "A solar electric propulsion mission for lunar power beaming". Specifically regarding the intensity of the beam on the lunar surface based on the description of the transmitter as given in the paper, assuming Gaussian beam divergence. The results at apogee appear to match Brandhorst, however at perigee the flux which I find is ~4 times larger than shown in the paper. The differences in the results may come from assumed beam quality (assumed to be perfect in my case) or the incident angle of the beam on the receiver. Furthermore, it is suggested but not stated that Brandhorst is considering an ~18 m diameter receiver.

**Comment by darianvp** [comment]
Based on the peer review, an additional task came up to wrap the functions already developed into a design tool that can be used to give a preliminary idea of the performance of different laser architectures.

**Comment by MatthewGrim** [comment]
So some tools that might be useful to start off with:
1. If I aim to get X amount of power to a target area, for a laser of a given wavelength, and diameter, what power would I need, and at what altitude to deliver this power. What would the area of the receiver region be?

2. If I were to aim to deliver X amount of power to a specified receiver area, what type of laser of a given wavelength could achieve this at an altitude greater than Y? What would the power need to be?

**Comment by darianvp** [comment]
RoverPower:

This analysis is in reference to a 10 W lunar rovers being charged using a SPS which provides a very large surface beam size (on the order of km) so that multiple rovers can be targeted simultaneously. The power can either be laser (assumed 850 nm for best compatibility with GaAs cells) or microwave (122 um for wireless power transfer).

I first looked at how significant Gaussian beam divergence is for the case where a 10-100 kW transmitter is used to create a spot on the lunar surface with a 10 W/m^2 flux.  With conservation of flux, I am able to find that the possible relative increase in beam radius (Rs/Rt) is on the order of 10 - 100 (meaning the beam radius on the surface, Rs, is 10 - 100 times larger than at transmitter, Rt), and thus the relative increase in area (As/At) is 100-10000. Therefore, if a large spot size is required (km-scale) a high power laser and/or large transmitter area is required.
![10w_surfacebeamdivergence](https://user-images.githubusercontent.com/38875772/39564565-0a415d46-4eb5-11e8-8062-f449c2146c67.png)

After approaching the problem from the perspective of the desired power on the surface, I looked at what how to achieve a surface beam size on the order of km. To do so I assumed a relative increase in the beam radius of 1e6, such that if Rt = 1e-3, then Rs = 1e3, and the result is a beam on the lunar surface which covers a minimum area of 2km in diameter. Using this condition and the equation for Gaussian beam divergence, I am able to determine the necessary separation of the transmitter from the target (ie. the orbital altitude of a SPS) for both the laser and microwave wavelengths. The upper limit on the target distance/altitude is set at the distance between the moon and the Earth (3.84e8 m). Another possibility for the upper bound is the distance from the moon to the L1 point (5.82e7 m). The result shows the a microwave SPS could fly much closer to the moon and still achieve a large surface beam size, and that the smaller the transmitter aperture size, the lower the required altitude.
![altitude_largesurfacebeam](https://user-images.githubusercontent.com/38875772/39564863-293b611e-4eb6-11e8-98e7-4329201ac7f5.png)

Lastly, I wanted to consider the power density in the beam which I described in the previous section (1e6 increase in radius from transmitter to surface). I found that a 10-100 kW transmitter power results in surface flux of << 1 W/m2. Thus I bumped the power up to 100 MW so that a surface flux of > 10 W/m2 could be achieved.

![surfaceflux_largebeam](https://user-images.githubusercontent.com/38875772/39565046-c7ac12ee-4eb6-11e8-8d9d-677606ca1c38.png)

The next step is to develop scripts that generalize this use case analysis so that a design space for potential SPS architectures can be identified.

**Comment by darianvp** [comment]
In the SPS design tool, I developed two functions to answer the following questions:
1. For a transmitter with X wavelength (ex. NIR laser, microwave) and a desired power flux density at the lunar surface, at what altitude must the SPS fly, and what is the resulting surface beam size? The script solves for altitude and beam size as a function of the transmitter aperture size and power. based on the user input for wavelength and surface flux. Only altitude results between 100 - 58000 km (very low lunar orbit up to the L1 point) are considered, since these are feasible lunar orbits. Below are the resulting feasible transmitter design spaces for a NIR laser (850 nm, high compatibility with GaAs solar cells) and microwave radiation (100 um) when the surface power flux is set to 10 W/m2.

![laser_choosewl sf](https://user-images.githubusercontent.com/38875772/39581669-66efa908-4eec-11e8-866c-b1a930ec186f.png)

![microwave_choosewl sf](https://user-images.githubusercontent.com/38875772/39581686-72c127de-4eec-11e8-89d1-b85df0529a70.png)

2. For a desired beam diameter of X and a power flux of Y at the lunar surface, what are the required transmitter size and power? The script calculates the transmitter power requirement directly based on the user inputs, and then evaluates the feasible design space for the transmitter size as a function of radiation wavelength and transmitter altitude. A quadratic solution is solved for transmitter radius, and the result is a solution which has two branches. However the only physical solutions are the ones with a transmitter diameter that is smaller than the surface beam diameter. Below are the potential transmitter sizes for a 1 km surface beam diameter and 10 W/m2 surface flux.  The result is a 78 kW transmitter with an aperture from 0.1 - 10 m, transmitting in the vis - microwave spectrum. X-axis is logarithm of wavelength.

![transsize_choosesbd sf_78kw](https://user-images.githubusercontent.com/38875772/39582257-d7fd61ca-4eed-11e8-9991-efca91e41144.png)

**Comment by darianvp** [comment]
Concerning application of this study to lunar rovers:

The AMALIA rover (proposed in 2010 by Alberto Della Torre, et al. for the Google Lunar X Prize Challenge) sports five strings of 24 triple-junction solar cells for generating power. Excerpt:

![microrover_solarcell_layout](https://user-images.githubusercontent.com/38875772/39615682-d0ef3a54-4f77-11e8-9155-08f5cffada0c.PNG)

For a micro-rover application such as this, it is likely that COTS cells, such as those made for CubeSats, would be selected. The size of these cells is on the order of 80 x 90 mm (https://www.cubesatshop.com/product/cubesat-solar-panels/), for a total power-generating area of 0.864 m2. The efficiency of such cells is generally assumed to be 30%.

The AMALIA design team specifies that their rover consumes between 7.2 W (hibernation) and 100 W (active). Excerpts:

![rover_hibernation_power](https://user-images.githubusercontent.com/38875772/39615739-230caa38-4f78-11e8-9aa8-714ab914c8ba.PNG)

![rover_active_power](https://user-images.githubusercontent.com/38875772/39615740-23296ec0-4f78-11e8-8522-c2f8e360fe90.PNG)

Thus to power this rover via solar power satellite, the necessary surface beam flux (Phi) is given by the equation:

![codecogseqn](https://user-images.githubusercontent.com/38875772/39615847-977bd8b2-4f78-11e8-8fc0-e62d4186e99d.gif)

where P is the required power of the rover, A is the total solar cell area, and Eta is the cell efficiency. Thus for the AMALIA rover, the required flux is:

Phi = 27.8 W/m2 (hibernation)
Phi = 385.8 W/m2 (active)

**Comment by darianvp** [comment]
This design tool is tailored to the rover application described in the previous comment. The script can be used to determine the "worst-case" scenario for an SPS system which delivers a 400 W/m2 flux, at 850 nm, to a receiver with a 1 m diameter (which approximately describes the power required for the operational mode of the AMALIA rover). The transmitter power is immediately determined based on the desired surface beam diameter and power flux. Then compatible altitudes for the SPS orbiter and sizes for the transmitter aperture are determined via Gaussian beam divergence. The result of the calculation is a design for a low-power (314 W transmitter), low-altitude (185 km) SPS architecture which can power one AMALIA lunar rover (100 W) in operational mode. This result is considered "worst case" since in reality a higher power transmitter could be used, in which case either a larger power density (same altitude) or beam size (higher altitude) could be achieved. In reality, the altitude 185 km is likely too low for an actual SPS application due to eclipsing. Will need to incorporate lower limit on compatible altitudes (upper is the L1-Moon) in order to select designs which are not as prone to eclipsing.

The likelihood of using a very large surface beam for simultaneously powering a small fleet of rovers in hibernation mode (10 W) can also be considered with this tool. Setting the desired flux to 30 W/m2 and varying the beam size, one can find that the required transmitter power increases quickly with the desired surface beam diameter. A realistic region in the design space exists for a beam size on the order of 30 m, for which a 21 kW transmitter flying at an altitude of 5500 km is required. A larger surface beam diameter (on the order of 1 km has been discussed as an interesting application for rover fleets) requires incredibly high power, due to the relatively high power flux requirement.

**Comment by MatthewGrim** [comment]
Nice work -I'm closing off this issue. If you come back to it, make sure the scripts you've written have relevant examples in them.

**Comment by darianvp** [comment]
SPS_DesignTool_v2 update:

Script is modified to determine the required transmitter power, and compatible orbital altitudes and transmitter aperture sizes based on the user's desired surface beam flux, and surface beam size (or receiver size). 

Transmitter power is calculated strictly based off the user input. The solar panel area required to gather that much power from the sun (assuming nominal flux of 1367 W/m2 from the sun, and 40% efficiency for the pv cells) is determined (also assuming 70% conversion efficiency for the transmitter, and 95% efficiency for the power management and distribution).

Then a linspace variable for the transmitter diameter, spanning 1 mm up to the desired surface beam diameter is defined, and required altitude is calculated for each transmitter size. The altitudes below 50 km and above 58200 km (L1 point) are filtered out, and the compatible range is returned in a plot. The minimum and maximum compatible altitudes are printed, along with the corresponding transmitter size. 

Two examples from the script, using a 850 nm wavelength for a laser transmitter:

![sps_design - smallrecarea](https://user-images.githubusercontent.com/38875772/40164788-c7e06cba-59ba-11e8-9de9-41dbc9b0ded4.png)

The above plot are the compatible altitudes/transmitter sizes for a surface beam diameter of 1 m. The transmitter power and solar collector area varies independently based on the desired surface beam flux. The altitude falls to 0 km as the transmitter size approaches the surface beam size, however with this size of transmitter diameter, beam divergence is small and thus virtually any altitude within 400 km would be suitable (leads to a 1.09 m diameter surface beam)

![sps_design medrecarea](https://user-images.githubusercontent.com/38875772/40164848-ecc68ba4-59ba-11e8-9b24-51382256ca5a.png)

The above plot shows the compatible altitude/transmitter sizes for a surface beam diameter of 250 m. The large surface beam size leads to a wider available design space for SPS altitude and transmitter size. However a very high power transmitter is generally required for a large surface beam size with moderate power flux density.

The same simulations can be run for microwave SPS transmitters. The results which change are the compatible transmitter diameter / altitude combos (since the wavelength influences divergence) and the total solar array size required (since electric-to-microwave conversion efficiency is better than for lasers, about 80%).
