### ISSUE TITLE
Add constraint on power storage requirements to be able to charge for consecutive access to blackout periods

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#21]
The blackout constraints are too forgiving at low altitude orbits because the model does not take into account the requirement to charge the rover before a blackout period occurs. This issue add this additional constraint to the one-to-one model.

**Comment by darianvp** [comment]
Its debatable whether this constraint is necessary since the maximum blackout event duration constraint already ensures that there are no events during which the rover would run out of power provided it begins the event with a full battery. Determining how the rover gets a full battery falls into the domain of rover operations design (appropriately scheduling exploratory activities and charging activities based on sunlight and SPS availability). Charging is not a fundamental requirement of the constrained SPS design. 

The main concern with this issue should perhaps be identifying and flagging back-to-back long blackout events which are broken up by a very brief active or sunlit event.

**Comment by darianvp** [comment]
I have generated the data for minimum active time for the 1SPS and 2SPS systems for the south pole. 1SPS:

![min_active south pole](https://user-images.githubusercontent.com/38875772/43308737-ccb4a382-9182-11e8-98c0-1894b6eb6e19.png)

2SPS:

![min_active south pole 2sps](https://user-images.githubusercontent.com/38875772/43308958-99172102-9183-11e8-9f62-51f4f93b5d9a.png)

This could maybe be used to for the constraint, ie. remove designs for which the minimum active event duration is not long enough to charge a fully drained battery.  In this case the minimum event duration could be estimated as the ratio of the rover battery capacity to the operational power of the rover, since it is assumed that the SPS supplies at least that much power during active times.

![codecogseqn 24](https://user-images.githubusercontent.com/38875772/43308012-5b0e2ba6-9180-11e8-9304-b15850e0f58b.gif)


However this constraint formulation is relatively tight for some of the targets considered.
Sorato: Tmin = 1.77 hrs
AMALIA: Tmin = 1.00 hrs
Curiosity: Tmin = 5.93 hrs

As mentioned in the previous comment, the formulation would likely be improved by identifying brief "power available" event (either sunlight or SPS) which are sandwiched between two long blackouts. This approach should then also take into account the rates of charging with sunlight and SPS power, and the sequencing of active/sunlit/blackout periods.

**Comment by MatthewGrim** [comment]
Based on Darian's comments - the hardest one to process would be the gold standard, but the current method is actually not a bad first pass ... let's see if I can do better with the sequential approach tomorrow.

**Comment by MatthewGrim** [comment]
So as a first pass, what I've done is take the total active time, supporting blackout periods, and the total time in blackout, and multiplied each by the minimum power supply the rover could receive, and its hibernation power requirements respectively. The ratio of these numbers gives an average ratio of the power delivered to survive the lunar night compared to the power delivered during it. If this number is greater than 1, we should be in the green.

For an AMALIA rover optimisation, we get something like 3.6 times the power required is delivered on average.

**Comment by MatthewGrim** [comment]
# Something wrong with min active time
For many simulations in the plots above, the minimum active time is 0.0 ... how can this be possible? A 0.0 length active time is not an access period. Something must be wrong with the algorithms.

**Comment by MatthewGrim** [comment]
# Update after fix to zero active time print outs
After fixing the 0 active time points that were due to errors in combining events, I've now started to plot all the statistics for blackouts and active times. It can be seen that the standard deviation and mean are smaller for active times. This doesn't mean that the rover cannot be charged to survive the lunar night, as the power balance plot below. which shows the energy delivered / the energy required during blackouts, shows there is a net energy surplus.

![event_data](https://user-images.githubusercontent.com/14801964/43766105-e621dec2-9a31-11e8-9e9b-203c3bce3071.png)

![power_balance](https://user-images.githubusercontent.com/14801964/43766129-f1c215c6-9a31-11e8-974f-2a37272bd6b5.png)

**Comment by MatthewGrim** [comment]
# Is this enough to say we survive the lunar night?
Using the statistics we currently have from the design tool, it's as good as we've got. Similar to what other members of the team have suggested, we may want to pick out a single design point, and see if we can survive the lunar night, by ordering the events, and power delivered in time. Plotting this will show when the rover has a net surplus, and if it ever runs out of power. 

I am going to do this, after I have chosen a few design points using the code as it stands. The priority at the moment is to write up what we have now into something that can be presented. After that we will do the more detailed analysis and see if we can add it to what we have.

**Comment by MatthewGrim** [comment]
@darianvp let me know what you think of this issue, if you're interested - no pressure

**Comment by MatthewGrim** [comment]
This issue was completed in #29
