### ISSUE TITLE
Validate that 30000km apogee is the best apogee for the satellite chosen by Brandhorst

### ISSUE THREAD

**Issue by MatthewGrim** [MatthewGrim/Lunar_SPS#5]
In the Brandhorst paper, circular and elliptical orbits of a single satellite are explored at altitudes up to 55,000km. It is claimed that 30,000km is the best apogee for a two year coverage time.

This issue documents the validation of this claim. It aims to:
1. Run simulations of a single target and satellite at different orbit altitudes.
2. Determine maximum eclipse times and total coverage times for each.
3. Compare best orbit against Brandhorst.
(4. Consider how this kind of optimisation might need to change for lunar rover exploration.)

**Comment by darianvp** [comment]
Ran simulation to study the total active time for SPS (set of available access periods within which the satellite is illuminated and the target is eclipsed) targeting a lunar site at 45N, as a function of the apogee altitude of the orbit (with perigee altitude fixed at 500 km).  The results do support Brandhorst's claim that the 30000 km apogee is an ideal candidate, since the access time appears to become saturated above this threshold. The interesting oscillatory behavior above 30000 km could be investigating by increasing the resolution of the data points. A plot of the data is shown below, with resolution of 5000 km.

![acces_vs_apogee](https://user-images.githubusercontent.com/38875772/39921034-ba3bf19c-5519-11e8-87b5-250a8100fab3.png)

**Comment by darianvp** [comment]
I've updated the script to provide the total blackout duration for a give perigee/apogee altitude orbit, over the simulation duration of 2 years. Furthermore, I added to the script so that I can look at the effect of varying the perigee on the total access and blackout times. The results are shown below. The perigee altitude is varied from 100 km to 5000 km (with resolution of 100 km below 500 km, and 1000 km resolution above 1000 km) with constant apogee altitude 30000 km. The apogee is varied from 1000 to 55000 km  (with resolution of 1000 km below 5000 km, and 5000 km resolution above 5000 km) with constant perigee altitude 500 km. 

From the plots shown (top-left, top-middle, showing total access time) it appears as though the orbit with 500 km perigee altitude and 30000 km apogee altitude is a good selection, and perhaps maybe even optimal although it is difficult to tell from this limited view of the design space and relatively low resolution. It would be best to have a full two dimensional array of orbit configurations (perigee altitude vs apogee altitude). It might also be worthwhile to look at the strangely behaving regions of these functions (low altitude perigee, high altitude apogee) with higher resolution (ie. printing out access and lighting event times for more orbits).

![orbit_study1](https://user-images.githubusercontent.com/38875772/39986811-204fd34a-5763-11e8-93fc-c08762608571.png)


The right-hand-most plots show the total sum of SPS active and black out periods for a given orbit, as a percentage of the total two year duration of the simulation. What this shows is that the sum of total active SPS duration with the total blackout duration accounts for slightly less than half the total simulation duration (during the rest of the time, the target is sunlit).

The method for calculating the total blackout duration relies on a function I wrote which determines periods (start, end, duration) in which the SPS cannot access the target. In some cases (access period data sets for lower altitude orbits) the sum of the no coverage duration and access time duration is not consistent, indicating some time is lost in the conversion from access event to no coverage events (function get_times_without_coverage). At most this error is a total of 5.4 hours. The bug is likely in determining the final no_coverage event, which may overlap with the end of the simulation.

**Comment by darianvp** [comment]
I have updated the script to calculate the maximum blackout duration (defined as intersection of events when SPS is not active, and the target is in eclipse) for a variety of orbits, as opposed to total black out time over two year period.

![access-blackout-equator-vs-apogee-perigee](https://user-images.githubusercontent.com/38875772/40367314-4cd38110-5dd9-11e8-9870-c741a7446a9c.png)

With respect to this metric, the 1000 km perigee 30000 km apogee orbit is the best data point presented. This is also the case in the previous study, where total blackout time is considered.

**Comment by MatthewGrim** [comment]
Nice validation work - I'm going to leave this issue open, in case you can manage to get the 2D parameter scan done with programmatic use of STK.

**Comment by MatthewGrim** [comment]
I'm closing this issue now, because with the time we have left this is a low priority issue, and the validation is sufficient enough for us to believe our use of orbital simulations.
